### ISSUE TITLE
Support multiple structs in one macro block?

### ISSUE THREAD

**Issue by ShayBox** [AlexanderHarrison/inline_default#2]
Could multiple structs in one macro block be supported? instead of wrapping every struct in its own block
![image](https://user-images.githubusercontent.com/9505196/221127186-a6b2a714-989d-4557-a212-b3aef63be3c8.png)
![image](https://user-images.githubusercontent.com/9505196/221127250-acce02c4-3f6c-40c1-8b0a-6afa992704b1.png)

**Comment by AlexanderHarrison** [comment]
Sure, that's simple. I've published a new version.
